"""Add password authentication support

Revision ID: 5f8ce94f4fcf
Revises: 9f7797d979af
Create Date: 2025-11-15 19:05:31.656618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8ce94f4fcf'
down_revision = '9f7797d979af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.alter_column('oauth_provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('oauth_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('oauth_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('oauth_provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
