"""Refactor to Association Object pattern

Revision ID: 9f7797d979af
Revises: c98e158630e0
Create Date: 2025-11-15 18:40:18.617746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7797d979af'
down_revision = 'c98e158630e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('num_attempts')
        batch_op.drop_column('status')
        batch_op.drop_column('date_attempted')

    with op.batch_alter_table('user_problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_attempted', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('num_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_problems', schema=None) as batch_op:
        batch_op.drop_column('num_attempts')
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('date_attempted')

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_attempted', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('num_attempts', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
